apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
spec:
  selector:
    app: flaskapp
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
spec:
  selector:
    matchLabels:
      app: flaskapp
  replicas: 4
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: sakib8899/flaskapp
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
